[package]
name = "PasteBot"
version = "0.1.0"
authors = ["Juan Potato <hasantiny@gmail.com>"]

[dependencies]
tg_botapi = "0.1.2"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
rusqlite = "0.9.5"
rust-crypto = "0.2"

